<?php
require_once '../auth_check.php';
requireRole(['admin', 'reception']);

$visit_id = $_GET['visit_id'] ?? '';
// In a real app, we fetch visit details here to show Name/Doctor on receipt
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Billing</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .invoice-box {
            max-width: 800px; margin: auto; padding: 30px; border: 1px solid #eee; background: white;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }
        @media print { 
            body * { visibility: hidden; }
            .invoice-box, .invoice-box * { visibility: visible; }
            .invoice-box { position: absolute; left: 0; top: 0; width: 100%; border: none; }
            .no-print { display: none; }
        }
    </style>
</head>
<body class="bg-light py-5">
    
    <div class="container text-center no-print mb-4">
        <a href="dashboard.php" class="btn btn-secondary">Back to Dashboard</a>
        <button onclick="window.print()" class="btn btn-primary">Print Receipt</button>
    </div>

    <div class="invoice-box shadow-sm">
        <div class="row mb-4 border-bottom pb-3">
            <div class="col-8">
                <h2 class="fw-bold text-primary">CITY HOSPITAL</h2>
                <small><?php echo HOSPITAL_ADDRESS; ?></small>
            </div>
            <div class="col-4 text-end">
                <h4 class="text-muted">RECEIPT</h4>
                <p>#<?php echo $visit_id; ?></p>
            </div>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Description</th>
                    <th class="text-end">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>OPD Consultation Fee</td>
                    <td class="text-end">PKR 2,000.00</td>
                </tr>
                <tr>
                    <td>Registration Charges</td>
                    <td class="text-end">PKR 500.00</td>
                </tr>
                <tr class="fw-bold fs-5 border-top">
                    <td>Total Paid</td>
                    <td class="text-end">PKR 2,500.00</td>
                </tr>
            </tbody>
        </table>

        <div class="mt-5 pt-3 border-top text-center text-muted small">
            <p>Generated by Reception Desk | <?php echo date('Y-m-d H:i'); ?></p>
            <p>Thank you for choosing City International Hospital.</p>
        </div>
    </div>

</body>
</html>